{% set version = '0.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-influencer
  version: {{ version|replace("-", "_") }}

source:
  fn: influenceR_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/influenceR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/influenceR/influenceR_{{ version }}.tar.gz
  sha256: 4fc9324179bd8896875fc0e879a8a96b9ef2a6cf42a296c3b7b4d9098519e98a

build:
  merge_build_host: True  # [win]
  number: 1003
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
    - llvm-openmp                # [osx]
  host:
    - r-base
    - r-matrix >=1.1_4
    - r-igraph >=1.0.1
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-matrix >=1.1_4
    - r-igraph >=1.0.1
    - llvm-openmp                # [osx]

test:
  commands:
    - $R -e "library('influenceR')"           # [not win]
    - "\"%R%\" -e \"library('influenceR')\""  # [win]

about:
  home: https://github.com/rcc-uchicago/influenceR
  license: GPL-2
  summary: Provides functionality to compute various node centrality measures on networks. Included
    are functions to compute betweenness centrality (by utilizing Madduri and Bader's
    SNAP library), implementations of Burt's constraint and effective network size (ENS)
    metrics, Borgatti's algorithm to identify key players, and Valente's bridging metric.
    On Unix systems, the betweenness, Key Players, and bridging implementations are
    parallelized with OpenMP, which may run faster on systems which have OpenMP configured.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
