appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: L5TbZOLR1bA+09CVz4Ny31BK7QalQxckbHTmWGSxJLobRSFQMlX8K87/F659FiwqT8SYadVpAECZ0DsKD0uEuHAAB0ZlpPnJpsEMYP4vXRA3/31ZnCz11uXwKrvTIgXmUGtu4mJawOkOKLjLDl17HN/AQZcQbe44nG3M5X8T8nykQdQFajszaBwAJORJZMh0vFYcBo/bq8Binv1JLOmMxDcQA0z1pPpWnIxJSaSxRpa3VThu717QtxOnbUfznKxkog1MsGaDCQZZt4aAUQgIRThitsy/vjUeh366IjfSI88koweiMNRmD0Xdethg8+HmUKWwRTbvIy1iCD83L1EQAsj6AZvGEEVrIEODqGEjQIi+A8gAzdP1PXycnuaK1e3pycqG4U2/NpWAmU7ws03ieLnRTYf573spPGXjSm6X+zLk5HZwLyDX0l7cdvbLHuomuPE/odsUV537IKOVYs9h8FHMViMWgOsyt5NPbQQe1SuSOWqoUD/G1jeELKaRWp8PI7nl1KGPpuyswzck9GUn0ZybMzggW5FiLXerHFqoFDPHoN7yluGUDt6JQJx2WK/egxxqVnrOixfhMRV55gMK5VJn1dGtapO2CrV/xCYg7VyovzllQrtjW8g0UI4QBet9bitAtcH0Udn/gZs8llCPvGR2NXGSGikaAaV/zDVHzlI=}
